config/routes.rb
Cet::Application.routes.draw do




  root :to => 'home#show', :as => 'home'
  match '/auth/:provider/callback' => 'sessions#create', :as => 'login_callback'
  match '/auth/failure', :to => 'sessions#failure'
  resource :session

  match '/login' => 'sessions#login', :as => 'login'
  match '/logout' => 'sessions#destroy', :as => 'logout'
  match '/login/cas/validate' => 'sessions#validate', :as => 'service_validate'
  match '/home/bylaws' => 'home#bylaws', :as => 'bylaws'
  match '/home/aboutus' => 'home#aboutus', :as => 'aboutus'
  match '/:school' => 'schools#show', :as => 'school'
  match '/:school/projects' => 'schools#projects', :as => 'school_projects'
  match '/search/new' => 'search#index', :as => 'search'
  match '/profile/:uid' => 'users#show', :as => 'profile'
  match '/profile/:uid/edit' => 'users#edit', :as => 'edit_profile'
  match '/profile/:uid/picture' => 'users#update_profile_picture', :as => 'update_profile_picture'
  match '/profile/:uid/picture/destroy' => 'users#destroy_profile_picture', :as => 'destroy_profile_picture'
  match '/project/new' => 'projects#new', :as => 'new_project'
  match '/project/:pid' => 'projects#show', :via => :get, :as => 'project'
  match '/project/:pid/edit' => 'projects#edit', :as => 'edit_project'
  match '/project/:pid' => 'projects#destroy', :via => :post, :as => 'destroy_project'
  match '/project/:pid/edit/collaborators' => 'projects#edit_collaborators', :via => :get, :as => 'edit_collaborators'
  match '/project/:pid/edit/collaborators' => 'projects#add_collaborator', :via => :post, :as => 'add_collaborator'
  match '/project/:pid/edit/collaborators/:cid' => 'projects#destroy_collaborator', :via => :post, :as => 'destroy_collaborator'
  match '/project/:pid/comments' => 'comments#create', :via => :post, :as => 'create_comment'
  match '/project/:pid/comments/:comid' => 'comments#destroy', :via => :post, :as => 'destroy_comment'
  match '/events/new' => 'events#new', :as => 'new_event'
  match '/events/all' => 'events#index', :as => 'events' 
  match '/events/:event_id/edit' => 'events#edit', :as => 'edit_event'  
  match '/events/:event_id/update' => 'events#update', :as => 'update_event' 
  match '/events/:event_id/delete' => 'events#delete', :as => 'delete_event'

  match '/project/:pid/docs' => 'documents#create', :as => 'create_doc'
  match '/project/:pid/docs/:did/destroy' => 'documents#destroy', :as => 'destroy_doc'
    







end

app/models/user.rb
  class User < ActiveRecord::Base

  attr_accessible :uid, :name, :email, :school, :major, :gradyear, :aboutme, :admin, :avatar, :avatar_file_name

  validates :email, :presence => true, :uniqueness => true, :email_format => {:message => "is not in a valid format!"}
  validates :school, :presence => true

  belongs_to :school
  has_and_belongs_to_many :projects, :uniq => true

  # User deletion causes all created projects to be destroyed
  has_many :created_projects, :class_name => 'Project', :foreign_key => "creator_id", :dependent => :destroy
  has_many :comments, :dependent => :destroy

  # for Paperclip file gem
  has_attached_file :avatar,
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :bucket => "cet-aii"
  
  image_types = ['image/png', 'image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/tiff', 'image/x-png']
  validates_attachment_content_type :avatar, :content_type => image_types

  def self.find_or_create_from_auth_hash(auth_hash)
    # create a new user or retreive the user if he already exists
    @user = User.find_by_uid(auth_hash[:uid])
    if @user.nil?
      #TODO: once multiple schools are registered with CET, School field should be set dynamically. For now, default to Berkeley.
      @user = User.create!(:uid => auth_hash[:uid], :name => auth_hash[:info][:name], :email => auth_hash[:info][:email], :school => School.find_by_uri('berkeley'), :admin => false, :avatar => nil)
    end
    return @user
  end

  def self.search(search)
    if search != nil
      find(:all, :conditions => ['lower(email) LIKE ? OR lower(name) LIKE ?', "%#{search}%".downcase, "%#{search}%".downcase])
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :set_current_user, :set_is_mine, :except => :index

  def set_is_mine
    @is_mine = @user.id.to_s == params[:uid]
  end

  def show
    @profile = User.find_by_id(params[:uid])
    @projects = @user.projects.order("updated_at DESC")
  end

  def edit
    if not @is_mine
      flash[:error] = "Permission denied..."
      redirect_to profile_path and return
    end
    if params[:profile]
      # The form has been submitted - update all the fields
      params[:profile].each do |att, value|
        @user[att] = value
      end

      if @user.save
        flash[:notice] = "Your profile was successfully edited!"
        redirect_to profile_path(@user.id) and return
      else
        flash[:error] = "Sorry, something went wrong with editing your profile."
        redirect_to edit_profile_path and return
      end
    end
  end

  def update_profile_picture
    @user.attributes = params[:user]
    if @user.save
      flash[:notice] = "Profile picture updated successfully"
      redirect_to profile_path(@user.id)
    else
      flash[:error] = "Profile picture update not successful; please make sure you have chosen a valid image filetype"
      redirect_to edit_profile_path(@user.id)
    end
  end

  def destroy_profile_picture
    @user.avatar.destroy if @user.avatar
    @user.avatar = nil
    @user.save
    redirect_to profile_path(@user.id)
  end

end

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Applied Innovations Institute &middot; </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->
    <%= stylesheet_link_tag "bootstrap" %>
    <%= stylesheet_link_tag "bootstrap-responsive" %>
  </head>

  <body>
    <div id="wrapper">
      
      <div id="header">
	<%= render "/navbar"%>
      </div>

      <div id="content">
	<br>
	<div class="row">
            <p class="text-info" style="font-size: 40pt; color: 0x000000">Edit Profile</p>
	</div>
	<hr class="featurette-divider">
	<div class="row">
	  
          <%= form_tag edit_profile_path(@user.id) do %>
	  
          <%= label :profile, :name, "Name:" %>
          <%= text_field :profile, 'name', :value => @user.name, :id => 'name' %>
	  
          <%= label :profile, :major, "Major:" %>
          <%= text_field :profile, 'major', :value => @user.major, :id => 'major' %>
	  
          <%= label :profile, :gradyear, "Graduation Year:" %>
          <%= text_field :profile, 'gradyear', :value => @user.gradyear, :id => 'gradyear' %>
	  
          <%= label :profile, :aboutme, "About Me:" %>
          <%= text_area :profile, 'aboutme', :value => @user.aboutme, :id => 'aboutme', :class => 'field span6', :rows => 7 %>
	  
	  <br>
          <%= submit_tag "Update Profile", {:class => "btn btn-primary btn-medium", :id => 'updateprofile' } %>
	  
          <% end %>
	</div>
	
	<hr class="featurette-divider">
	<div class = "row">
	  <%= form_for @user, :url => update_profile_picture_path(@user.id), :html => { :multipart => true } do |form| %>
	    <%= form.file_field :avatar %>
	    <%= submit_tag "Update Profile Picture", :class => "btn btn-primary" %>
	  <% end %>
	  <% if @user.avatar and @user.avatar.url != "/avatars/original/missing.png" %>
	    <%= button_to "Delete Profile Picture", destroy_profile_picture_path(@user.id), :class => "btn btn-danger", :confirm => "Are you sure?" %>
	  <% end %>
	</div>
	
      </div>

      <div id="footer">
	<%= render "/footer"%>
      </div>

    </div>
  </body>
</html>

app/views/users/new_project.html.erb
require "erb"

<html>
<head>
  <%= image_tag("logo.png") %>
  <title>Applied Innovations Institute</title>
  <%= stylesheet_link_tag "bootstrap" %>
</head>

<body>
  <h1>New Project</h1>

  <form>
  Name: <input type="text" name="name" size="5"><br>
  <p>Description: <textarea type="text" name="description" rows="5" cols="150">
  </textarea></p>
  
  Collaborator 1: <input type="text" name="collaborator1" size="30"><br>
  Collaborator 2: <input type="text" name="collaborator2" size="30"><br>
  Collaborator 3: <input type="text" name="collaborator3" size="30"><br>
  Collaborator 4: <input type="text" name="collaborator4" size="30"><br>
  <input type="submit" value="Submit">
  </form>

</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Applied Innovations Institute &middot; </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->

    <%= stylesheet_link_tag "bootstrap" %>
    <%= stylesheet_link_tag "bootstrap-responsive" %>
  </head>

  <body>
    <div id="wrapper">
      <div id="header">
        <%= render "/navbar"%>
      </div>

      <div id="content">

        <div class = "row pull-right">
          
        </div>

        <div class="row span-centered">
          <div class = "span4 offset2">
            <% if @user.avatar and @user.avatar.url != "/avatars/original/missing.png" %>
              <%= image_tag(@user.avatar.url, :height => "400") %>
            <% else %>
              <%= image_tag("goat.jpg", :width => "400") %>
            <% end %>
          </div>

          <div class = "span4">
            <table class="transparent">
              <thead align = "left">
    <tr>
      <th><h1><%= @profile.name %></h1> </th>
    </tr>
              </thead>
              <tbody>
    <tr align = "left">
                  <td> About Me: <br> <%= @profile.aboutme %></td>
    </tr>
              </tbody>
            </table>
            <br>

            <table class="table table-striped">
              <tbody>
                <tr>
                  <td>Email</td>
                  <td><%= @profile.email %></td>
                </tr>
                <tr>
                  <td>School</td>
                  <td><%= @profile.school.name %></td>
                </tr>
                <tr>
                  <td>Major</td>
                  <td><%= @profile.major %></td>
                </tr>
                <tr>
                  <td>Graduation Year</td>
                  <td><%= @profile.gradyear %></td>
                </tr>
              </tbody>
            </table>

           
          </div>

          <div class = "span 2">
            <%= button_to "Edit Profile", edit_profile_path(@user.id), {:class => "btn btn-warning btn-small" } if @is_mine %>
          </div>
  </div>
  
  <br><br><br>
  
  <% if @projects != [] %>
  <div class = "row span-centered">
          <div class = "span6 span-centered">
            <h2>Active Projects</h2>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Owner</th>
                  <th>Collaborators</th>
                  <th>Last Updated</th>
                </tr>
              </thead>
              <tbody>
    <% @projects.each do |project| %>
    <tr>
                  <td><%= link_to project.title, project_path(project.id) %></td>
                  <td><%= link_to project.creator.name, profile_path(project.creator.id) %></td>
                  <td><%= project.users.length %>
                  <td><%= time_ago_in_words(project.updated_at) %> ago</td>
    </tr>
    <% end %>
              </tbody>
            </table>
          </div>
  </div>
  <% end %>
      </div>
      
      <div id="footer">
  <%= render "/footer"%>
      </div>
      
    </div>
  </body>
</html>