config/routes.rb
Cet::Application.routes.draw do




  root :to => 'home#show', :as => 'home'
  match '/auth/:provider/callback' => 'sessions#create', :as => 'login_callback'
  match '/auth/failure', :to => 'sessions#failure'
  resource :session

  match '/login' => 'sessions#login', :as => 'login'
  match '/logout' => 'sessions#destroy', :as => 'logout'
  match '/login/cas/validate' => 'sessions#validate', :as => 'service_validate'
  match '/home/bylaws' => 'home#bylaws', :as => 'bylaws'
  match '/home/aboutus' => 'home#aboutus', :as => 'aboutus'
  match '/:school' => 'schools#show', :as => 'school'
  match '/:school/projects' => 'schools#projects', :as => 'school_projects'
  match '/search/new' => 'search#index', :as => 'search'
  match '/profile/:uid' => 'users#show', :as => 'profile'
  match '/profile/:uid/edit' => 'users#edit', :as => 'edit_profile'
  match '/profile/:uid/picture' => 'users#update_profile_picture', :as => 'update_profile_picture'
  match '/profile/:uid/picture/destroy' => 'users#destroy_profile_picture', :as => 'destroy_profile_picture'
  match '/project/new' => 'projects#new', :as => 'new_project'
  match '/project/:pid' => 'projects#show', :via => :get, :as => 'project'
  match '/project/:pid/edit' => 'projects#edit', :as => 'edit_project'
  match '/project/:pid' => 'projects#destroy', :via => :post, :as => 'destroy_project'
  match '/project/:pid/edit/collaborators' => 'projects#edit_collaborators', :via => :get, :as => 'edit_collaborators'
  match '/project/:pid/edit/collaborators' => 'projects#add_collaborator', :via => :post, :as => 'add_collaborator'
  match '/project/:pid/edit/collaborators/:cid' => 'projects#destroy_collaborator', :via => :post, :as => 'destroy_collaborator'
  match '/project/:pid/comments' => 'comments#create', :via => :post, :as => 'create_comment'
  match '/project/:pid/comments/:comid' => 'comments#destroy', :via => :post, :as => 'destroy_comment'
  match '/events/new' => 'events#new', :as => 'new_event'
  match '/events/all' => 'events#index', :as => 'events' 
  match '/events/:event_id/edit' => 'events#edit', :as => 'edit_event'  
  match '/events/:event_id/update' => 'events#update', :as => 'update_event' 
  match '/events/:event_id/delete' => 'events#delete', :as => 'delete_event'

  match '/project/:pid/docs' => 'documents#create', :as => 'create_doc'
  match '/project/:pid/docs/:did/destroy' => 'documents#destroy', :as => 'destroy_doc'
    







end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :name, :location, :startTime, :endTime, :school

  validates :name, :presence => true, :uniqueness => true
  validates :description, :presence => true
  validates :startTime, :presence => true
  validates :endTime, :presence => true

  belongs_to :school

  def self.search(search)
    if search != nil
      find(:all, :conditions => ['lower(name) LIKE ? OR lower(location) LIKE ? or lower(description) LIKE ?', "%#{search}%".downcase, "%#{search}%".downcase, "%#{search}%".downcase])
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def new
    @user = User.find(session[:user_id])
    if not @user.admin
      redirect_to school_path(@user.school.uri)
      return
    end

    event = params[:event]
    newEvent = Event.new
    startTime = DateTime.new(event['startTime(1i)'].to_i, event['startTime(2i)'].to_i, event['startTime(3i)'].to_i, event['startTime(4i)'].to_i, event['startTime(5i)'].to_i)
    endTime = DateTime.new(event['endTime(1i)'].to_i, event['endTime(2i)'].to_i, event['endTime(3i)'].to_i, event['endTime(4i)'].to_i, event['endTime(5i)'].to_i)
    if startTime > endTime
      flash[:error] = "The start date and time must come before the end date and time."
      redirect_to :action => 'index'
      return
    end
    
    newEvent.name = event[:name]
    newEvent.description = event[:description]
    newEvent.location = event[:location]
    newEvent.school_id = @user.school
    newEvent.startTime = startTime
    newEvent.endTime = endTime    
    success = newEvent.save
    
    if success
      flash[:notice] = "Event successfully created!"
    else
      flash[:error] = "One or more fields were left blank, please try again."
    end
    redirect_to :action => 'index'
      
  end

  def index
    @user = User.find(session[:user_id])
    if not @user.admin
      redirect_to school_path(@user.school.uri)
      return
    end

    @events = Event.where("school_id = ?", @user.school)
    @event = Event.new
  end

  def edit
    @user = User.find(session[:user_id])
    if not @user.admin
      redirect_to school_path(@user.school.uri)
      return
    end

    @event = Event.find(params[:event_id])
    @eid = params[:event_id]
  end

  def update
    @user = User.find(session[:user_id])
    if not @user.admin
      redirect_to school_path(@user.school.uri)
      return
    end

    event_info = params[:event]
    event = Event.find(params[:event_id])
    event.name  = event_info[:name]
    event.description = event_info[:description]
    event.location = event_info[:location]
    startTime = DateTime.new(event_info['startTime(1i)'].to_i, event_info['startTime(2i)'].to_i, event_info['startTime(3i)'].to_i, event_info['startTime(4i)'].to_i, event_info['startTime(5i)'].to_i)
    endTime = DateTime.new(event_info['endTime(1i)'].to_i, event_info['endTime(2i)'].to_i, event_info['endTime(3i)'].to_i, event_info['endTime(4i)'].to_i, event_info['endTime(5i)'].to_i)
    
    if startTime > endTime
      flash[:error] = "The start date and time must come before the end date and time."
      redirect_to edit_event_path(params[:event_id])
      return
    end

    event.startTime = startTime
    event.endTime = endTime
    success = event.save

    if success
      flash[:notice] = "Event successfully updated!"
    else
      flash[:error] = "One or more fields were left blank, please try again."
    end
    redirect_to :action => 'index'
  end

  def delete
    @user = User.find(session[:user_id])
    if not @user.admin
      redirect_to school_path(@user.school.uri)
      return
    end

    event = Event.find(params[:event_id])
    event.destroy
    redirect_to :action => 'index'
  end
end

app/views/events/edit.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <title>Applied Innovations Institute &middot; </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->
    <%= stylesheet_link_tag "bootstrap" %>
    <%= stylesheet_link_tag "bootstrap-responsive" %>
  </head>

  <body>
    <div id="wrapper">

      <div id="header"> 
	<%= render "/navbar"%>
      </div>

      <div id="content">
	<div class = "row">
	  <div align = "center">
	    <h2>Edit Event</h2>
	  </div>
	</div>
	
	<hr class="featurette-divider">
	<br>

	<div class = "row">
	  <div align = "center">
	    <%= form_for @event, :url => update_event_path(@eid) do |f| %>
	    
	    <%= f.label :name, "Name:" %>
	    <%= f.text_area :name, :class => 'field span6', :id => 'name', :rows => 1, :value => @event.name %>
	    
	    <%= f.label :description, "Enter a short description:" %>
	    <%= f.text_area :description, :class => 'field span6', :id => 'description', :rows => 6, :value => @event.description %>
	    
	    <%= f.label :location, "Location:" %>
	    <%= f.text_area :location, :class => 'field span6', :id => 'location', :rows => 1, :value => @event.location %>
	    
	    <br><br>
	    From: <%= f.datetime_select :startTime, :prompt => {:hour => @event.startTime.hour, :minute => @event.startTime.min}, :ampm => true, :minute_step => 15 %>
	    
	    <br>
	    Until: <%= f.datetime_select :endTime, :prompt => {:hour => @event.endTime.hour, :minute => @event.endTime.min}, :ampm => true, :minute_step => 15 %>
	    
	    <br><br> 
	    <%= f.submit "Update Event", {:class => "btn btn-primary btn-medium" } %>
	    
	    <% end %>
	  </div>
	</div>
      </div>
      
      <div id="footer">
	<%= render "/footer"%>
      </div>

    </div>
  </body>
</html>

app/views/events/index.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <title>Applied Innovations Institute &middot; </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->
    <%= stylesheet_link_tag "bootstrap" %>
    <%= stylesheet_link_tag "bootstrap-responsive" %>
  </head>

  <body>
    <div id="wrapper">

      <div id="header">
	<%= render "/navbar" %>
      </div>
      
      <div id="content">
	<div class = "row">
	  <div align = "center">
	    <h0>Upcoming Events</h0>
	  </div>
	</div>

	<br>
	
	<div class = "row">
	  <div align = "center">
	    <% @events.each do |event| %>
	    <h3><%= event.name %></h3>
	    <p class="ex"> <B>About:</B> <%= event.description %></p>
	    <p> <%= event.location %></p>
	    <p> Begins on <%= event.startTime.strftime("%B %d, %Y at %I:%M %p") %></p>
	    <p> And ends on <%= event.endTime.strftime("%B %d, %Y at %I:%M %p") %></p>
	    <table class="transparent">
	      <tr>
	      <td><%= button_to "Edit", edit_event_path(event.id), {:class => "btn btn-warning btn-medium" } %></td>
	      <td><%= button_to "Delete", delete_event_path(event.id), :class => "btn btn-danger btn-medium", :confirm => "Are you sure you wish to delete this event?" %></td>
	      <tr>
	    </table>
	    <hr class="event">
	    <% end %>
	  </div>
	</div>
	
	<div class = "row">
	  <div align = "center">
	    <h3>Create New Event</h3>
	  </div>
	</div>
	
	<div class = "row">
	  <%= form_for @event, :url => new_event_path() do |f| %>
	  
	  <%= f.label :name, "Name:" %>
	  <%= f.text_area :name, :class => 'field span6', :id => 'name', :rows => 1 %>
	  
	  <%= f.label :description, "Enter a short description:" %>
	  <%= f.text_area :description, :class => 'field span6', :id => 'description', :rows => 6 %>
	  
	  <%= f.label :startTime, "Start Date and Time:" %>
	  <%= f.datetime_select :startTime, :prompt => {:hour => 'Choose Hour', :minute => 'Choose Minute'}, :ampm => true, :minute_step => 15 %>
	  
	  <%= f.label :endTime, "End Date and Time:" %>
	  <%= f.datetime_select :endTime, :prompt => {:hour => 'Choose Hour', :minute => 'Choose Minute'}, :ampm => true, :minute_step => 15 %>
	  
	  <%= f.label :location, "Location:" %>
	  <%= f.text_area :location, :class => 'field span6', :id => 'location', :rows => 1 %>
	  
	  <br>
	  <%= f.submit "Create Event", {:class => "btn btn-primary btn-medium" } %>
	  <% end %>
	</div>
      </div>
      
      <div id="footer">
	<%= render "/footer" %>
      </div>
      
    </div>
  </body>
</html>