config/routes.rb
Cet::Application.routes.draw do




  root :to => 'home#show', :as => 'home'
  match '/auth/:provider/callback' => 'sessions#create', :as => 'login_callback'
  match '/auth/failure', :to => 'sessions#failure'
  resource :session

  match '/login' => 'sessions#login', :as => 'login'
  match '/logout' => 'sessions#destroy', :as => 'logout'
  match '/login/cas/validate' => 'sessions#validate', :as => 'service_validate'
  match '/home/bylaws' => 'home#bylaws', :as => 'bylaws'
  match '/home/aboutus' => 'home#aboutus', :as => 'aboutus'
  match '/:school' => 'schools#show', :as => 'school'
  match '/:school/projects' => 'schools#projects', :as => 'school_projects'
  match '/search/new' => 'search#index', :as => 'search'
  match '/profile/:uid' => 'users#show', :as => 'profile'
  match '/profile/:uid/edit' => 'users#edit', :as => 'edit_profile'
  match '/profile/:uid/picture' => 'users#update_profile_picture', :as => 'update_profile_picture'
  match '/profile/:uid/picture/destroy' => 'users#destroy_profile_picture', :as => 'destroy_profile_picture'
  match '/project/new' => 'projects#new', :as => 'new_project'
  match '/project/:pid' => 'projects#show', :via => :get, :as => 'project'
  match '/project/:pid/edit' => 'projects#edit', :as => 'edit_project'
  match '/project/:pid' => 'projects#destroy', :via => :post, :as => 'destroy_project'
  match '/project/:pid/edit/collaborators' => 'projects#edit_collaborators', :via => :get, :as => 'edit_collaborators'
  match '/project/:pid/edit/collaborators' => 'projects#add_collaborator', :via => :post, :as => 'add_collaborator'
  match '/project/:pid/edit/collaborators/:cid' => 'projects#destroy_collaborator', :via => :post, :as => 'destroy_collaborator'
  match '/project/:pid/comments' => 'comments#create', :via => :post, :as => 'create_comment'
  match '/project/:pid/comments/:comid' => 'comments#destroy', :via => :post, :as => 'destroy_comment'
  match '/events/new' => 'events#new', :as => 'new_event'
  match '/events/all' => 'events#index', :as => 'events' 
  match '/events/:event_id/edit' => 'events#edit', :as => 'edit_event'  
  match '/events/:event_id/update' => 'events#update', :as => 'update_event' 
  match '/events/:event_id/delete' => 'events#delete', :as => 'delete_event'

  match '/project/:pid/docs' => 'documents#create', :as => 'create_doc'
  match '/project/:pid/docs/:did/destroy' => 'documents#destroy', :as => 'destroy_doc'
    







end

app/models/project.rb
class Project < ActiveRecord::Base

  # mass assignment
  attr_accessible :title, :description, :creator, :school

  validates :title, :presence => true
  validates :description, :presence => true

  has_and_belongs_to_many :users, :uniq => true
  belongs_to :school
  belongs_to :creator, :class_name => "User", :foreign_key => "creator_id"
  has_many :documents, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  
  def add_collaborator(user)
    self.users << user
  end

  def add_collaborator_by_email(email)
    user = User.find_by_email(email)
    success = false
    begin
      self.users << user
      success = true
    rescue
    end if user
    return success
  end
  
  def self.search(search)
    if search != nil
      find(:all, :conditions => ['lower(title) LIKE ? OR lower(description) LIKE ?', "%#{search}%".downcase, "%#{search}%".downcase])
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :set_current_user
  before_filter :set_can_edit, :except => :new

  def new_or_edit
    # see if we are creating a new project or just editing an existing one
    if params[:pid]
      project = Project.find_by_id(params[:pid])
    else
      project = Project.new
      project.add_collaborator(@user)
      project.creator = @user
    end

    project_info = params[:project]
    project.title = project_info[:title]
    project.description = project_info[:description]
    project.school_id = @user.school

    success = project.save
    if success
      if params[:pid]
        flash[:notice] = "Project successfully edited!"
      else
        flash[:notice] = "Project successfully created!"
      end
      redirect_to project_path(project.id) and return
    end
    # if unsuccessful, flash an error
    if params[:pid]
      flash[:error] = "Sorry, something went wrong with editing this project."
      redirect_to edit_project_path(project.id)
    else
      flash[:error] = "Sorry, something went wrong with creating a new project."
      redirect_to new_project_path
    end
  end

  def new
    if params[:project]
      # process the form
      new_or_edit and return
    end
  end

  def edit
    if not @can_edit
      flash[:error] = "Permission denied..."
      redirect_to project_path(@project.id) and return
    end
    if params[:project]
      new_or_edit and return
    end
    @project = Project.find_by_id(params[:pid])
    @can_delete = false
    @can_delete = true if (@project.creator == @user or (@user.admin and @user.school_id == @project.school_id))
  end

  def show
    @project = Project.find_by_id(params[:pid])
    @comments = @project.comments.order("created_at DESC")
    @document = Document.new
  end

  def destroy
    @project = Project.find_by_id(params[:pid])
    # can only destroy if you are creator
    if @project.creator == @user
      if @project.destroy
        flash[:notice] = "Successfully deleted " + @project.title
        redirect_to school_path(@user.school.uri) and return
      else
        flash[:error] = "Oops, something went wrong with deleting " + @project.title
      end
    else
      flash[:error] = "You can't delete this project!"
    end
    redirect_to project_path(@project.id)
  end

  def edit_collaborators
    if not @can_edit
      flash[:error] = "Permission denied..."
      redirect_to project_path(@project.id) and return
    end
  end

  def add_collaborator
    if not @can_edit
      flash[:error] = "Permission denied..."
      redirect_to project_path(@project.id) and return
    end
    email = params[:collaborator]
    success = @project.add_collaborator_by_email(email)
    if success
      flash[:notice] = "Collaborator added!"
    else
      flash[:error] = "Invalid collaborator!"
    end
    redirect_to edit_collaborators_path
  end

  def destroy_collaborator
    if not @can_edit
      flash[:error] = "Permission denied..."
      redirect_to project_path(@project.id) and return
    end
    collaborator = User.find_by_id(params[:cid])
    if collaborator == @user or collaborator == @project.creator
      # You can't delete yourself or creator
      flash[:error] = "Oops, you can't do that!"
      redirect_to edit_collaborators_path(@project.id) and return
    end
    success = @project.users.delete(collaborator)
    if success
      flash[:notice] = "Collaborator deleted!"
    else
      flash[:error] = "Oops! Something went wrong."
    end
    redirect_to edit_collaborators_path(@project.id)
  end

end

app/views/projects/edit.html.erb
<html>
<head>
  <%= stylesheet_link_tag "bootstrap" %>
</head>

<body>

<div id="wrapper">
  <div id="header">
    <%= render "/navbar"%>
  </div>

  <div id="content">

    <div class = "row">
      <h2>Edit Project: <%= link_to @project.title, project_path(@project.id) %></h2>
    </div>


  <%= form_tag edit_project_path do %>
    <div class = "row table-centered">
    
      <%= label :project, :title, "Title:" %>
      <%= text_field :project, :title, :value => @project.title %>
    </div>

    <div class = "row table-centered">
      <%= label :project, :description, "Enter a short description:" %>
      <textarea class="field span8" id="project_description" name="project[description]" rows="6"><%= @project.description %></textarea>
    </div>

    <div class = "row table-centered">
      <div class = "span2 offset3">
        <%= submit_tag "Update Project", :class => "btn btn-primary" %>
        <% end %>
      </div>
      <div class = "span2">
        <%= button_to "Edit Collaborators", edit_collaborators_path(@project.id), :class => "btn btn-warning" %>
      </div>
      <div class = "span2">
        <%= button_to "Delete Project", (destroy_project_path(@project.id) if @can_delete), :class => "btn btn-danger", :confirm => "Are you sure you wish to delete this project?"%>
      </div>
    </div>
</div>

    <div id="footer">
      <%= render "/footer"%>
    </div>

  </div>

</body>
</html>

app/views/projects/edit_collaborators.html.erb
<html>
<head>
  <%= stylesheet_link_tag "bootstrap" %>
</head>

<body>
  <div id="wrapper">

    <div id="header"> 
      <%= render "/navbar"%>
    </div>



    <div id="content">
      <h1><%= link_to @project.title, project_path(@project.id) %></h1>
      <h2>Collaborators</h2>
      <br>

  <% @project.users.each do |user| %>
    <% # you have to make it so your own name and creator doesn't appear on this list %>
    <% if @user != user and user != @project.creator %>
      <p><%= user.email %></p>
      <%= button_to "Delete", destroy_collaborator_path(@project.id, user.id), :confirm => 'Are you sure you want to delete this collaborator?', :id => 'delete_' + user.id.to_s %>
      <% end %>
      <% end %>

      <h4> Enter the email address of the collaborator you'd like to add.</h4>
      
      <%= form_tag add_collaborator_path do %>
      <%= text_field_tag :collaborator %>
      <%= submit_tag "Add Collaborator", {:class => "btn btn-primary btn-medium" }  %>
      <% end %>
    </div>

    <div id="footer">
      <%= render "/footer"%>
    </div>

  </div>
</body>
</html>

app/views/projects/index.html.erb
<html>
<head>
    <meta charset="utf-8">
    <title>Applied Innovations Institute &middot; </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->
    <%= stylesheet_link_tag "bootstrap" %>
    <%= stylesheet_link_tag "bootstrap-responsive" %>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<body>
  <div id="wrapper">
    
    <div id="header"> 
      <%= render "/navbar"%>
    </div>

    <div id="content">
      <% form_tag projects_path, :method => 'get' do %>
      <p>
	<%= text_field_tag :search, params[:search] %>
	<%= submit_tag "Search", :name => nil %>
      </p>
      <% end %>
    </div>

    <div id="footer">
      <%= render "/footer"%>
    </div>

  </div>
</body>
</html>

app/views/projects/new.html.erb
<html>
<head>
    <meta charset="utf-8">
    <title>Applied Innovations Institute &middot; </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->
    <%= stylesheet_link_tag "bootstrap" %>
    <%= stylesheet_link_tag "bootstrap-responsive" %>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<body>
  <div id="wrapper">

    <div id="header">
      <%= render "/navbar"%>
    </div>

    <div id="content"> 
      <div class = "row">
	<div align = "center">
	  <h2>New Project</h2>
	</div>
      </div>
      
      <hr class="featurette-divider">
      
      <div class = "row">
	
	<%= form_tag new_project_path do %>
	
	<%= label :project, :name, "Title:" %>
	<%= text_field :project, 'title', :id => 'title' %>
	
	<%= label :project, :description, "Enter a short description:" %>
	<textarea class="field span6" id="description" name="project[description]" rows="6"></textarea>
	
	<br>
	<%= submit_tag "Create Project", {:class => "btn btn-primary btn-medium" } %>
	<% end %>
      </div>
    </div>

    <div id="footer">
      <%= render "/footer"%>
    </div>

  </div>
</body>
</html>

app/views/projects/search.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Applied Innovations Institute &middot; </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->

    <%= stylesheet_link_tag "bootstrap" %>
    <%= stylesheet_link_tag "bootstrap-responsive" %>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>

  <body>


    <%= render "/navbar"%>

    <hr class="featurette-divider">
      <!-- START THE FEATURETTES -->
      <div class="row">
        <div class = "span6 offset3">
          <h3><%= "Newest Projects by #{@name} students" %></h3>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Project Name</th>
                  <th>Project Owner</th>
                  <th>Date Created</th>
                </tr>
              </thead>
            <tbody>
              <% @school.projects.each do |project| %>
              <tr>
                <td>BLAH</td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>


      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2012 CET &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>

    <%= render "/footer"%>
<!-- /.container -->
  </body>
</html>

app/views/projects/show.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <title>Applied Innovations Institute &middot; </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->
    <%= stylesheet_link_tag "bootstrap" %>
    <%= stylesheet_link_tag "bootstrap-responsive" %>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>
    <div id="wrapper">

      <div id="header">
  <%= render "/navbar"%>
      </div>

  <div id="content">
  <div class = "row">
    <div align = "center">
      <h1><%= @project.title %></h1>
      <h5><%= button_to "Edit Project", edit_project_path(@project.id), :class => "btn btn-warning btn-medium" if @can_edit %></h5>
    </div>
  </div>
  <hr class="featurette-divider">

  <div class = "row">
    <div align = "center">
            <h4>Description</h4>
      <p class="ex"><%= @project.description %></p>
    </div>
  </div>

  <div class = "row">
    <div align = "center">
      <h4>Last Updated</h4>
      <p><%= time_ago_in_words(@project.updated_at) %> ago</p>
    </div>
  </div>

  <div class = "row">
    <div align = "center">
      <h4>Created</h4>
      <p><%= @project.created_at.to_formatted_s(:long) %></p>
    </div>
  </div>

  <div class = "row">
    <div align = "center">
      <h4>Collaborators</h4>
      <% @project.users.each do |user| %>
        <% if user != @user %>
            <p><%= link_to user.email, profile_path(user.id) %></p>
        <% end %>
      <% end %>
      <h5> <%= button_to "Edit Collaborators", edit_collaborators_path(@project.id), :method => :get, :class => "btn btn-warning btn-medium" if @can_edit %> </h5>
    </div>
  </div>

  <hr class="featurette-divider">
  <div class = "row">
    <div class = "span12" align=left>
      <h3 align=left>Project Documents</h3>
      <table class="table">
        <tbody>
<tr>
<%= form_for @document, :url => create_doc_path, :html => { :multipart => true } do |form| %>
  <td colspan=2><%= form.file_field :avatar %></td>
  <td colspan=3><%= text_field :document, "description", :placeholder => "add description...", :class => "input-xlarge", :id => "description"%></td>
  <td><%= submit_tag "Upload New File", :class => "btn btn-primary" %></td>
<% end %>
</tr>

<% @project.documents.each do |doc| %>
<tr>
  <td>
    <% if @can_edit%>
      <%= link_to doc.avatar_file_name, doc.avatar.url %>
    <% else %>
      <%= doc.avatar_file_name %>
    <% end %>
  </td>
  <td><%= doc.description %></td>
  <td><%= doc.avatar_file_size/1000 %>kB</td>
  <td>Uploaded By: <%= link_to doc.updater.name, profile_path(doc.updater.id) %></td>
  <td><%= time_ago_in_words(doc.avatar_updated_at) %> ago</td>
  <td><%= button_to "Delete File", destroy_doc_path(@project.id, doc.id), :class => "btn btn-danger btn-mini", :confirm => "Are you sure?" %></td>
</tr>
<% end %>

        </tbody>
      </table>
    </div>
  </div>

  <hr class="featurette-divider">
  <h3>Comments</h3>

  <div class="row">
    <div class="span10">
      <table class="table">
        <tbody>
    <tr>
      <%= form_tag create_comment_path do %>
      <td colspan=3><%= text_field :comment, :text, :placeholder => "add comment...", :class => "input-xxlarge", :id => "new_comment" %></td>
      <td><%= submit_tag "Add Comment", :class => "btn btn-primary" %></td>
      <% end %>
    </tr>

    <% @comments.each do |comment| %>
    <tr>
      <td><%= link_to comment.user.name, profile_path(comment.user.id) %></td>
      <td><%= comment.text %></td>
      <td><%= time_ago_in_words(comment.created_at) %> ago</td>
      <% if @can_edit or @user.id == comment.user.id %>
      <td><%= button_to "Delete Comment", destroy_comment_path(@project.id, comment.id), :class => "btn btn-danger btn-mini", :confirm => "Are you sure?" %></td>
      <% end %>
    </tr>
    <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div id="footer">
    <%= render "/footer"%>
  </div>

    </div>
  </body>
</html>